#!/usr/bin/env bash
set -euxo pipefail

ACTION=$2
case $ACTION in
start)
ssh -i $SSH_KEY $SSH_USER@review.dev.storj.io -p 29418 gerrit review "$(git rev-parse HEAD)" --message \"build $1 is started\" --tag autogenerated:gerrit-integration --label Verified=$3
;;

failure)
ssh -i $SSH_KEY $SSH_USER@review.dev.storj.io -p 29418 gerrit review "$(git rev-parse HEAD)" --message \"build $1 is failed\" --tag autogenerated:gerrit-integration --label Verified=$3
;;

success)
ssh -i $SSH_KEY $SSH_USER@review.dev.storj.io -p 29418 gerrit review "$(git rev-parse HEAD)" --message \"build $1 is finished successfully\" --tag autogenerated:gerrit-integration --label Verified=$3
;;

*)
echo “Action is missing”
exit 1

esac
